system:
  db-type: mysql
  cache-type: redis
  port: '80'
  env: 'product'  # Change to "develop" to skip authentication for development mode

mysql:
  username: root
  password: '123456'
  path: 'localhost:3306'
  dbname: 'gin_admin'
  config: 'charset=utf8mb4&parseTime=true&loc=Local&timeout=1s'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false

redis:
  addr: 'localhost:6379'
  password:
  db:

log:
  level: info
  format: console
  prefix: '[gin-admin]'
  director: log
  link-name: latest_log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

jwt:
  signing-key: 'gin-admin'

captcha:
  key-long: 4
  img-width: 120
  img-height: 40

casbin:
  model-path: './resource/rbac_model.conf'

baidumap:
  ip_location_url: "http://api.map.baidu.com/location/ip?ak="
  ak: "vMA1yoLuen421tmxsV8fFCGStbertF10"